version: '2'
services:
    
    wordpress:
      image: wordpress
      ports:
         - 8080:80
      environment:
        WORDPRESS_DB_PASSWORD: blank
    
    db:
       image: mariadb
       environment:
         MYSQL_ROOT_PASSWORD: blank